// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnowOps.Api.Data;

#nullable disable

namespace SnowOps.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("defect_public_id_seq")
                .StartsAt(1000L);

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AreaCode")
                        .HasColumnType("text")
                        .HasColumnName("area_code");

                    b.Property<string>("AreaName")
                        .HasColumnType("text")
                        .HasColumnName("area_name");

                    b.Property<short>("CoveragePercent")
                        .HasColumnType("smallint")
                        .HasColumnName("coverage_percent");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("DefectType")
                        .HasColumnType("smallint")
                        .HasColumnName("defect_type");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<DateTimeOffset?>("FixedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fixed_at");

                    b.Property<DateTimeOffset>("FoundAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("found_at");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<short>("LocationType")
                        .HasColumnType("smallint")
                        .HasColumnName("location_type");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<long>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("public_id")
                        .HasDefaultValueSql("nextval('defect_public_id_seq')");

                    b.Property<int>("RiskR")
                        .HasColumnType("integer")
                        .HasColumnName("risk_r");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("defect", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.DefectEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DefectId")
                        .HasColumnType("uuid")
                        .HasColumnName("defect_id");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<short?>("FromStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("from_status");

                    b.Property<short?>("ToStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("DefectId");

                    b.ToTable("defect_event", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.DefectFixProof", b =>
                {
                    b.Property<Guid>("DefectId")
                        .HasColumnType("uuid")
                        .HasColumnName("defect_id");

                    b.Property<int>("AfterPhotosCount")
                        .HasColumnType("integer")
                        .HasColumnName("after_photos_count");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("ConfirmedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by_user_id");

                    b.HasKey("DefectId");

                    b.HasIndex("ConfirmedByUserId");

                    b.ToTable("defect_fix_proof", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.DefectPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<Guid>("DefectId")
                        .HasColumnType("uuid")
                        .HasColumnName("defect_id");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint")
                        .HasColumnName("kind");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<byte[]>("Sha256")
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_provider");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("defect_photo", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("CenterLat")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lat");

                    b.Property<double>("CenterLon")
                        .HasColumnType("double precision")
                        .HasColumnName("center_lon");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.HasKey("Id");

                    b.ToTable("district", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.WeatherObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<decimal>("Precipitation3hMm")
                        .HasColumnType("numeric")
                        .HasColumnName("precipitation_3h_mm");

                    b.Property<string>("Raw")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw");

                    b.Property<bool>("SnowOrIceLast3h")
                        .HasColumnType("boolean")
                        .HasColumnName("snow_or_ice_last_3h");

                    b.Property<decimal>("Snowfall3hMm")
                        .HasColumnType("numeric")
                        .HasColumnName("snowfall_3h_mm");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<decimal>("TempC")
                        .HasColumnType("numeric")
                        .HasColumnName("temp_c");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("weather_observation", (string)null);
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.Defect", b =>
                {
                    b.HasOne("SnowOps.Api.Domain.Entities.District", "District")
                        .WithMany("Defects")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowOps.Api.Domain.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId");

                    b.Navigation("District");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.DefectEvent", b =>
                {
                    b.HasOne("SnowOps.Api.Domain.Entities.AppUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowOps.Api.Domain.Entities.Defect", "Defect")
                        .WithMany("Events")
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.DefectFixProof", b =>
                {
                    b.HasOne("SnowOps.Api.Domain.Entities.AppUser", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowOps.Api.Domain.Entities.Defect", "Defect")
                        .WithOne("FixProof")
                        .HasForeignKey("SnowOps.Api.Domain.Entities.DefectFixProof", "DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedBy");

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.DefectPhoto", b =>
                {
                    b.HasOne("SnowOps.Api.Domain.Entities.Defect", "Defect")
                        .WithMany("Photos")
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnowOps.Api.Domain.Entities.AppUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defect");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.WeatherObservation", b =>
                {
                    b.HasOne("SnowOps.Api.Domain.Entities.District", "District")
                        .WithMany("WeatherObservations")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.Defect", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("FixProof");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("SnowOps.Api.Domain.Entities.District", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("WeatherObservations");
                });
#pragma warning restore 612, 618
        }
    }
}
